export const FETCH_INTERVIEWS = 'FETCH_INTERVIEWS';
export const NEW_INTERVIEW = 'NEW_INTERVIEW';
export const SHOW_INTERVIEW = 'SHOW_INTERVIEW';
export const DELETE_INTERVIEW = 'DELETE_INTERVIEW';
export const UPDATE_INTERVIEW = 'UPDATE_INTERVIEW';
